### ISSUE TITLE
Support kube scheduler ComponentConfig

### ISSUE THREAD

**Issue by damemi** [openshift/cluster-kube-scheduler-operator#197]
I know right now we support policy config through the operator, but don't know what our status is on componentconfig. So making this issue to track that and look into it

**Comment by damemi** [comment]
There was some discussion in our channel about whether we'll ever actually need to support CC. I asked in sig-scheduling and it seems that yes, someday policy config will be deprecated but CC is still a long way from GA. So, this is something we should keep in mind for our operator but more of a long term goal

**Comment by damemi** [comment]
Upstream tracking issue to deprecate policy in favor of componentconfig: https://github.com/kubernetes/kubernetes/issues/87526

**Comment by damemi** [comment]
As of 1.19, the `v1alpha1` scheduler config library is removed, which is what our operator depends on. We'll need to update our scheduler to use ComponentConfig by then

Currently, we observe the scheduler config by giving the scheduler a configmap that has the policy in it (see https://github.com/openshift/cluster-kube-scheduler-operator/blob/82b5c997d78cbc2cdf8a3b661f82f59b43cc04fa/pkg/operator/configobservation/scheduler/observe_scheduler.go#L17)

In `v1alpha2`, the `AlgorithmSource` field is deprecated, meaning we can no longer simply pass a configmap name that holds a `Policy` file. Instead, we'll need to pass that observed config directly as a [`SchedulerProfile`](https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/kube-scheduler/config/v1alpha2/types.go#L94). Note that this means documentation should be updated to reflect that the scheduler will now be configured by Plugin (filter/score/etc) componentconfig and NOT policy (predicates/priorities)

For reference, currently when you try to run a >1.19 kube-scheduler image with our operator you get the following error right away:
```
no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1alpha1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:30"
```

Updating our KubeSchedulerConfiguration to v1alpha2 (https://github.com/openshift/cluster-kube-scheduler-operator/pull/245) fixes it, but trying to pass a custom config results in this error:
```
strict decoder error for {"algorithmSource":{"policy":{"configMap":{"name":"policy-configmap","namespace":"openshift-kube-scheduler"}}},"apiVersion":"kubescheduler.config.k8s.io/v1alpha2","clientConnection":{"kubeconfig":"/etc/kubernetes/static-pod-resources/configmaps/scheduler-kubeconfig/kubeconfig"},"kind":"KubeSchedulerConfiguration","leaderElection":{"leaderElect":true,"resourceLock":"configmaps","resourceNamespace":"openshift-kube-scheduler"}}
: v1alpha2.KubeSchedulerConfiguration.ReadObject: found unknown field: algorithmSource, error found in #10 byte of ...|thmSource":{"policy"|..., bigger context ...|{"algorithmSource":{"policy":{"configMap":{"name":"policy-configmap"|...
```

Which shows the need to switch from our current `algorithmSource` config reconciliation to `schedulerProfiles`

cc @ingvagabund ^ what we talked about

**Comment by damemi** [comment]
To update this, the legacy Policy config is still available under `kubescheduler.config.k8s.io/v1`, but the flags associated with consuming it are still being deprecated. https://github.com/kubernetes/kubernetes/pull/91420 promotes v1alpha2 componentconfig to v1beta1, and https://github.com/openshift/cluster-kube-scheduler-operator/pull/250 adds a metric to measure how many users are actually using custom configs through the operator.

**Comment by damemi** [comment]
PR transitioning us to the new componentconfig: https://github.com/openshift/cluster-kube-scheduler-operator/pull/255

**Comment by damemi** [comment]
Should also note: Policy API is scheduled to be removed for 1.23: https://github.com/kubernetes/kubernetes/issues/92143

**Comment by damemi** [comment]
/close
with the implementation of https://github.com/openshift/enhancements/blob/master/enhancements/scheduling/scheduler-profiles.md (https://github.com/openshift/cluster-kube-scheduler-operator/pull/307) we can close this

**Comment by mmgaggle** [comment]
@damemi Can we revisit this? The enhancement proposal (#307) hasn't been updated since Jan 2019. Is there another way to do this?

**Comment by damemi** [comment]
@mmgaggle the enhancement should definitely be updated to reflect its current state (it is now implemented). Thank you for pointing this out

**Comment by mmgaggle** [comment]
Excellent! I'm experimenting with this right now, but I'm having trouble figuring out how to configure a plugin. It looks like you can adjust the weights via policy, and can enable / disable plugins. What I'm interested in specifically is the ability to configure / use `PodTopologySpread` along the lines of this 

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#cluster-level-default-constraints

It's not clear to me if this can be done, and if it can, how I might do that. Any ideas?

**Comment by damemi** [comment]
@mmgaggle I'm very sorry that this thread slipped off my radar, to answer your question though the cluster-level default constraints are currently not possible with the default kube-scheduler in OCP. If you wish to configure settings that require a custom KubeSchedulerConfiguration in OpenShift, right now your only option is to run a secondary scheduler in the cluster.
