### ISSUE TITLE
Error setting custom scheduler image with IMAGE env var

### ISSUE THREAD

**Issue by damemi** [openshift/cluster-kube-scheduler-operator#263]
Trying to deploy a custom scheduler through the operator using the provided `${IMAGE}` env var may fail due to `${IMAGE}` being parsed for both the init container (`wait-for-host-port`) and the operand kube-scheduler.

In [`starter.go`](https://github.com/openshift/cluster-kube-scheduler-operator/blob/4aa17b3179e746dabdd23a0bcea8c7485b05507d/pkg/operator/starter.go#L98), the `IMAGE` env var is passed to [`NewTargetConfigController`](https://github.com/openshift/cluster-kube-scheduler-operator/blob/4aa17b3179e746dabdd23a0bcea8c7485b05507d/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L282-L302) which uses it to replace the scheduler image in the pod yaml. However, the pod yaml uses `${IMAGE}` in both the [init container](https://github.com/openshift/cluster-kube-scheduler-operator/blob/4aa17b3179e746dabdd23a0bcea8c7485b05507d/bindata/v4.1.0/kube-scheduler/pod.yaml#L15) and the [scheduler container](https://github.com/openshift/cluster-kube-scheduler-operator/blob/4aa17b3179e746dabdd23a0bcea8c7485b05507d/bindata/v4.1.0/kube-scheduler/pod.yaml#L15).

What this means is if I build my own custom scheduler image and specify it in the env var, the scheduler pod will fail to launch if my custom scheduler is built in a way that doesn't provide `/usr/bin/timeout`. This should not be a requirement for the operand to provide additional commands (ie, all that should be required is the `kube-scheduler` command, although the operator additionally assumes that [`hyperkube`](https://github.com/openshift/cluster-kube-scheduler-operator/blob/4aa17b3179e746dabdd23a0bcea8c7485b05507d/bindata/v4.1.0/kube-scheduler/pod.yaml#L31) will also be provided. Given that the scheduler is not built through hyperkube upstream anymore, this becomes problematic for users. So additionally, the `command` should be customizable).

```
$ oc get all -n openshift-kube-scheduler
pod/openshift-kube-scheduler-ci-ln-lx8b05k-f76d1-szgz7-master-0   0/2     Init:CreateContainerError   0          32s
pod/openshift-kube-scheduler-ci-ln-lx8b05k-f76d1-szgz7-master-1   2/2     Running                     0          179m
pod/openshift-kube-scheduler-ci-ln-lx8b05k-f76d1-szgz7-master-2   2/2     Running                     1          3h

$ oc describe pod/openshift-kube-scheduler-ci-ln-lx8b05k-f76d1-szgz7-master-0 -n openshift-kube-scheduler
...
Events:
  Type     Reason   Age   From                                         Message
  ----     ------   ----  ----                                         -------
  Normal   Pulling  40s   kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Pulling image "docker.io/mdame/kube-scheduler-119"
  Normal   Pulled   34s   kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Successfully pulled image "docker.io/mdame/kube-scheduler-119"
  Warning  Failed   34s   kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Error: container create failed: time="2020-07-20T18:03:00Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/usr/bin/timeout\\\": stat /usr/bin/timeout: no such file or directory\""
container_linux.go:348: starting container process caused "exec: \"/usr/bin/timeout\": stat /usr/bin/timeout: no such file or directory"
  Warning  Failed  33s  kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Error: container create failed: time="2020-07-20T18:03:01Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/usr/bin/timeout\\\": stat /usr/bin/timeout: no such file or directory\""
container_linux.go:348: starting container process caused "exec: \"/usr/bin/timeout\": stat /usr/bin/timeout: no such file or directory"
  Warning  Failed  22s  kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Error: container create failed: time="2020-07-20T18:03:12Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/usr/bin/timeout\\\": stat /usr/bin/timeout: no such file or directory\""
container_linux.go:348: starting container process caused "exec: \"/usr/bin/timeout\": stat /usr/bin/timeout: no such file or directory"
  Normal   Pulled  9s (x3 over 33s)  kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Container image "docker.io/mdame/kube-scheduler-119" already present on machine
  Warning  Failed  9s                kubelet, ci-ln-lx8b05k-f76d1-szgz7-master-0  Error: container create failed: time="2020-07-20T18:03:25Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/usr/bin/timeout\\\": stat /usr/bin/timeout: no such file or directory\""
container_linux.go:348: starting container process caused "exec: \"/usr/bin/timeout\": stat /usr/bin/timeout: no such file or directory"
```

As a user, I would like to be able to change the `IMAGE` and `command` for *only* the kube-scheduler container in order to run a custom scheduler image through the operator. However, this comes with the risk that users may run a broken scheduler and break their clusters. Given that the `IMAGE` env var isn't directly provided in the operator config, this seems sufficiently "hidden" as an advanced administrator/developer feature. It's also already provided, in all of our operators, but it's broken in this one.

With our operator only supporting deprecated Policy config, there is no other way for any user to customize the default scheduler.

/kind bug

**Comment by damemi** [comment]
/cc @ingvagabund 
Could you take a look at the logic for replacing this, and see if it's simple enough to fix so that the init container and the scheduler container images aren't coupled?

**Comment by ingvagabund** [comment]
Yeah, lemme check it out.
/assign

**Comment by ingvagabund** [comment]
`IMAGE` in the deployment manifest will get reset by CVO. Also, configuring an image with a custom scheduler is more suitable for the CR. We can have the operator just use the CR provided image in case it's set and replace the default image provided through the env.
