### ISSUE TITLE
Is policy config file going to be supported?

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/cluster-kube-scheduler-operator#44]
In 4.0, do we plan to support policy config file for scheduler, if yes, how do we plan to do it with operators, if not, we need some clean up in the documentation.

**Comment by wjiangjay** [comment]
@ravisantoshgudimetla FYI, https://github.com/openshift/cluster-kube-scheduler-operator/pull/45/files

**Comment by ravisantoshgudimetla** [comment]
Addressed through

To be clear, we are not supporting policy file but we are going to support policy configmap.
