### ISSUE TITLE
How can I enable a scheduler extender in a way that is supported by the scheduler operator.

### ISSUE THREAD

**Issue by closms** [openshift/cluster-kube-scheduler-operator#475]
I see the configuration in the configmap openshift-kube-scheduler/config

>  config.yaml: |
>    {"apiVersion":"kubescheduler.config.k8s.io/v1beta3","clientConnection":{"kubeconfig":"/etc/kubernetes/static-pod-resources/configmaps/scheduler-kubeconfig/kubeconfig"},"kind":"KubeSchedulerConfiguration","leaderElection":{"leaderElect":true,"leaseDuration":"137s","renewDeadline":"107s","resourceLock":"configmapsleases","resourceNamespace":"openshift-kube-scheduler","retryPeriod":"26s"}}

but attempts to overwrite it are immediately reverted.

I want to add in a scheduler extender.

I found this section of the [openshift documentation](https://docs.openshift.com/container-platform/4.11/operators/operator-reference.html#cluster-kube-scheduler-operator_cluster-operators-ref) which suggests that the scheduler operator's config observer can merge together sparse json snippets to form the actual configuration. But I'm unable to figure out the details.

Thanks ahead,
Mike

**Comment by lance5890** [comment]
if u just want to do some test, u could simply stop the cluster-version-operator(change the deployment replica to 0) and cluster-kube-scheduler-operator， then u can try to edit the coinfig

**Comment by closms** [comment]
Thanks Ian.

Is there a way to do this and keep those operators running?

A scheduler extender has a few benefits over a secondary scheduler.
- No need for cluster wide RBAC
- No kubelet race condition.
- Any policy implemented in the extender will be respected by the default scheduler, since the extender works with the default scheduler.
- Its easier to support multiple versions of OCP.  Different versions of OCP have different versions of the default scheduler (1.19, 1.23, 1.25). A scheduler extender works with all of these versions. When using a secondary scheduler, i'd have to provide a different build for each of these versions.

**Comment by knelasevero** [comment]
The operator will keep reconciling and recurrently keep that file the way that the operator is meant to keep it.

Configuration for the scheduler is only available through the 

```
apiVersion: config.openshift.io/v1
kind: Scheduler
```

custom resource. That part of the documentation that you linked only says that the operator merges a default config with whatever you configure in the custom resource. This is also described in the readme of this repository.

**Comment by closms** [comment]
Hi Lucas.

Thanks for the reply. It looks like using the [policy field](https://docs.openshift.com/container-platform/4.8/nodes/scheduling/nodes-scheduler-default.html) of the Scheduler resource was deprecated in OCP 4.10. Using it causes the operator to complain

> TargetConfigControllerDegraded: "configmap": scheduler Policy config has been removed upstream, this field remains for CRD compatibility but does nothing now. Please use a Profile instead (defaulting to LowNodeUtilization).

The Profile section seems to be specific to scoring.  I'll continue to poke at it to see if what i'm trying to do is doable and supported.

**Comment by closms** [comment]
Well. As far as I can tell. The code to manage the scheduler's KubeSchedulerConfiguration is here

https://github.com/openshift/cluster-kube-scheduler-operator/blob/ee2906225bda7bf2aefc8eb338ba841142cc04da/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L167-L199

I don't see a designed/supported way to inject a scheduler extender. I'm going to assume that there isn't one.  I'll close this issue.
